# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c77cc87e4417b2fdd388e81f5a20166cd36180b79ec1cd428eaf67826ec98d7370f653667ac0c92db95d6f2aa82fa14eb1c510a760f1e73a63a09112e44a9156

test:
  secret_key_base: 3c7b40f67b49535970981ea50f8dfb5532acb1b3e94e057bfafaab970b1537b88ac3502a0519fe01032500ab7a34091f89fed1b3c6dcf6f5f126b257e9ea8c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
